### PR TITLE
code:

### PR DESCRIPTION
**Pull request by hezlog**
Changes proposed in this pull request:
1.Fix wrong public key;
2.Fix default file Encoding;

Any expected problems concerning backwards compatibility of existing plugins?  
No

Any expected problems concerning backwards compatibility of existing user settings?  
No

Does this break existing user workflows?  
No

### CODE REVIEW

**Comment by Kittyfisto** [comment]
Thanks for the PR!
Can you explain the reasoning to switching the encoding to `Encoding.Default`?

Regarding the changes to the AssemblyInfo.cs - they are correct, however this doesn't currently pass CI because the official tailviewer builds are built against a different certificate that's not checked into the repo; The build step doesn't change the Public Key definitions in the AssemblyInfo.cs file, so that's why CI doesn't pass just yet.

I'll have to fix that first before this particular fix can be merged.

**Comment by hezlog** [comment]
Chinese Coding Display Error.

**Comment by Kittyfisto** [comment]
@hezlog Would you be willing to share an example log file with me so I can better understand this problem?

**Comment by Kittyfisto** [comment]
@hezlog I also have an alternative offer for you :)

I've just pushed a change for tailviewer which allows users to configure the default encodings via the settings page as follows:

image

This is not meant to be final (and I appreciate all and every input), but it might help you: The second entry in the "default text file encoding" combo-box is the `Encoding.Default` value which should map to whatever default encoding is configured on your system.

If you change this setting from `Auto detect` to the desired one (**and** restart tailviewer), the encoding errors should no longer appear for you (as this would be virtually identical to the change you propose, without requiring any hardcoded value anymore).

Please let me know if this helps.

**Comment by Kittyfisto** [comment]
Last followup: I've finally taken the time to align all public keys.

Everyone who checks out the latest sources of tailviewer will be able to compile, test and run tailviewer. However the resulting binary will be signed using a "developer" strong name key file as opposed to official releases which are signed using a secret key file.

This way people who want to contribute are no longer put of by receiving strange compile errors due to my previous negligence.

Thanks again for bringing this to my attention.

I'm closing this PR as both issues have been solved in separate commits.

**Comment by hezlog** [comment]
thank you!

**Pull request closed without merging**
